# Generated by Django 4.0 on 2021-12-22 20:45

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Trad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("fr_content", models.CharField(blank=True, max_length=255)),
                ("fr_content_rich", ckeditor.fields.RichTextField(blank=True)),
                ("en_content", models.CharField(blank=True, max_length=255)),
                ("en_content_rich", ckeditor.fields.RichTextField(blank=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trads",
                        to="trads.section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img_link", models.ImageField(blank=True, upload_to="img/%y%m")),
                ("img_alt", models.CharField(blank=True, max_length=255)),
                ("Key", models.CharField(blank=True, max_length=255)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imgs",
                        to="trads.section",
                    ),
                ),
            ],
        ),
    ]
