# Generated by Django 4.0 on 2022-01-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="img_link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
