# Generated by Django 4.0 on 2022-02-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0002_alter_img_img_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="img",
            old_name="Key",
            new_name="key",
        ),
    ]
