# Generated by Django 4.0 on 2022-02-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0004_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="img",
            name="img_link",
        ),
        migrations.AddField(
            model_name="img",
            name="screenshot",
            field=models.FileField(default="", upload_to="option/web/img"),
            preserve_default=False,
        ),
    ]
