# Generated by Django 4.0 on 2022-02-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0005_remove_img_img_link_img_screenshot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Img",
        ),
    ]
