# Generated by Django 4.0 on 2022-02-24 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0006_delete_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255)),
                ("screenshot", models.FileField(upload_to="option/web/img")),
                ("img_alt", models.CharField(blank=True, max_length=255)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imgs",
                        to="trads.section",
                    ),
                ),
            ],
        ),
    ]
