# Generated by Django 4.0 on 2022-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0008_alter_img_screenshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.IntegerField(default=0)),
            ],
        ),
    ]
