# Generated by Django 4.0 on 2022-04-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0009_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="index",
            field=models.IntegerField(default=0),
        ),
    ]
