# Generated by Django 4.0 on 2022-10-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0010_tax_index"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tax",
        ),
    ]
