# Generated by Django 4.1.3 on 2022-12-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trads", "0011_delete_tax"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestedElementDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("🇫🇷 France", "Fr"),
                            ("🇬🇧 Anglais", "En"),
                            ("🇪🇸 Espagnol", "Es"),
                            ("🇮🇹 Italien", "It"),
                            ("🇩🇪 Allemand", "De"),
                            ("🇨🇳 Chinois", "Cn"),
                        ],
                        default="🇫🇷 France",
                        max_length=32,
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
