# Generated by Django 3.2.16 on 2022-11-14 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0006_userinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingInfo",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="authie.useraccount",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MailJet", "Mailjet"), ("Courier", "Courier")],
                        default="MailJet",
                        max_length=128,
                    ),
                ),
                ("apikey", models.CharField(blank=True, max_length=255, null=True)),
                ("apipass", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPersonalInfo",
            fields=[
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="authie.useraccount",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("postal", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
