# Generated by Django 3.2.16 on 2022-11-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0007_auto_20221114_1843"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("Off", "Off"),
                    ("Trial", "Trial"),
                    ("Basic", "Basic"),
                    ("Plus", "Plus"),
                    ("Premium", "Premium"),
                ],
                default="Trial",
                max_length=128,
            ),
        ),
    ]
