# Generated by Django 3.2.16 on 2022-11-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0008_useraccount_provider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="provider",
            new_name="customer_type",
        ),
    ]
