# Generated by Django 3.2.16 on 2022-11-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0009_rename_provider_useraccount_customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinginfo",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mailinginfo",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
