# Generated by Django 3.2.16 on 2022-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0010_auto_20221123_0857"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpersonalinfo",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userpersonalinfo",
            name="conact_email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userpersonalinfo",
            name="phone",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userpersonalinfo",
            name="rib",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="userpersonalinfo",
            name="siret",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
