# Generated by Django 4.1.3 on 2023-02-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0012_gamedefaults_featurespermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featurespermission",
            name="owner",
        ),
    ]
