# Generated by Django 4.1.3 on 2023-02-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0013_remove_featurespermission_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedefaults",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamedefaults",
            name="music",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
