# Generated by Django 4.1.3 on 2023-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0015_gamedefaults_policy_rules_gamedefaults_regulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamedefaults",
            name="bg_image_ingame_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamedefaults",
            name="intro_image_url_landscape",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gamedefaults",
            name="intro_image_url_portrait",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
