# Generated by Django 4.0 on 2022-09-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="game_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="game_theme",
            new_name="theme",
        ),
        migrations.RemoveField(
            model_name="game",
            name="request_cp",
        ),
        migrations.AddField(
            model_name="game",
            name="can_replay",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="facebook",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="insta",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="logo_company",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="mailjet_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="qr_location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="game",
            name="twitter",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="game",
            name="emblem",
            field=models.CharField(default="", max_length=32),
        ),
    ]
