# Generated by Django 4.0 on 2022-10-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_rename_game_name_game_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="end_text",
            field=models.BooleanField(default=True),
        ),
    ]
