# Generated by Django 4.0 on 2022-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_end_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="end_text",
            field=models.CharField(default="", max_length=255),
        ),
    ]
