# Generated by Django 4.0 on 2022-10-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_alter_game_end_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="img",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
