# Generated by Django 4.0 on 2022-10-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_price_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="winnedprice",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winned_prices",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="winnedprice",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winned_prices",
                to="games.price",
            ),
        ),
    ]
