# Generated by Django 4.0 on 2022-10-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_winnedprice_game_alter_winnedprice_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="end_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="facebook",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="insta",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="logo_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="mailjet_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="twitter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
