# Generated by Django 4.0 on 2022-10-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_game_end_text_alter_game_facebook_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="tel",
            new_name="phone",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="cp",
        ),
    ]
