# Generated by Django 4.0 on 2022-10-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0008_rename_tel_lead_phone_remove_lead_cp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="can_reveceive_email",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
