# Generated by Django 4.0 on 2022-10-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0009_alter_lead_can_reveceive_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="winnedprice",
            name="creation_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
