# Generated by Django 4.0 on 2022-10-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0010_winnedprice_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="price_won",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="games.winnedprice",
            ),
        ),
    ]
