# Generated by Django 4.0 on 2022-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0013_game_losing_factor"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefusedLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="timezone",
            field=models.CharField(
                choices=[("Europe/Paris", "Eu Paris"), ("US/Hawaii", "Us Hawaii")],
                default="Europe/Paris",
                max_length=128,
            ),
        ),
    ]
