# Generated by Django 4.0 on 2022-11-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0015_refusedlead_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_type",
            field=models.CharField(
                choices=[("curtain", "Curtain"), ("Calendar", "Calendar")],
                default="curtain",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="RequestedElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_elements",
                        to="games.game",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_elements",
                        to="games.lead",
                    ),
                ),
            ],
        ),
    ]
