# Generated by Django 4.0 on 2022-11-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0016_alter_game_game_type_requestedelement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="game_type",
        ),
        migrations.RemoveField(
            model_name="game",
            name="theme",
        ),
    ]
