# Generated by Django 4.0 on 2022-11-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0002_remove_gametype_game_type_remove_skin_skin_and_more"),
        ("games", "0017_remove_game_game_type_remove_game_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="dash.gametype",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skins",
                to="dash.skin",
            ),
        ),
    ]
