# Generated by Django 3.2.16 on 2022-11-08 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0018_game_game_type_game_theme"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="theme",
            new_name="skin",
        ),
        migrations.CreateModel(
            name="WinnableTimeRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winnalbe_time_range",
                        to="games.price",
                    ),
                ),
            ],
        ),
    ]
