# Generated by Django 3.2.16 on 2022-11-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0019_auto_20221108_1208"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="email_template",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
