# Generated by Django 3.2.16 on 2022-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0020_price_email_template"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ("-id",)},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ("-id",)},
        ),
        migrations.RemoveField(
            model_name="winnabletimerange",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="winnabletimerange",
            name="start_date",
        ),
        migrations.AddField(
            model_name="winnabletimerange",
            name="day",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winnabletimerange",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
