# Generated by Django 3.2.16 on 2022-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0021_auto_20221115_1757"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="start_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
