# Generated by Django 3.2.16 on 2022-11-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0022_game_start_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="start_text",
            new_name="closing_text",
        ),
        migrations.AddField(
            model_name="game",
            name="opening_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
