# Generated by Django 4.1.3 on 2022-12-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0025_remove_game_font"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="consolation_price",
            field=models.BooleanField(default=False),
        ),
    ]
