# Generated by Django 4.1.3 on 2022-12-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0026_price_consolation_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="end_text",
        ),
    ]
