# Generated by Django 4.1.3 on 2022-12-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0028_extragamelanguage_pricestrads_gametrads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extragamelanguage",
            name="id_ref",
        ),
        migrations.AddField(
            model_name="extragamelanguage",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pricestrads",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_traductions",
                to="games.price",
            ),
        ),
        migrations.AlterField(
            model_name="extragamelanguage",
            name="lang",
            field=models.CharField(
                choices=[
                    ("Francais", "Fr"),
                    ("Anglais", "En"),
                    ("Italien", "It"),
                    ("Allemagne", "De"),
                    ("Espagne", "Es"),
                    ("China", "Cn"),
                ],
                default="Anglais",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="extragamelanguage",
            constraint=models.UniqueConstraint(
                fields=("game", "lang"), name="game_and_lang"
            ),
        ),
    ]
