# Generated by Django 4.1.3 on 2022-12-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0029_remove_extragamelanguage_id_ref_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestedElementDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[
                            ("🇫🇷 France", "Fr"),
                            ("🇬🇧 Anglais", "En"),
                            ("🇪🇸 Espagnol", "Es"),
                            ("🇮🇹 Italien", "It"),
                            ("🇩🇪 Allemand", "De"),
                            ("🇨🇳 Chinois", "Cn"),
                        ],
                        default="🇫🇷 France",
                        max_length=32,
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="extragamelanguage",
            name="lang",
            field=models.CharField(
                choices=[
                    ("🇫🇷 France", "Fr"),
                    ("🇬🇧 Anglais", "En"),
                    ("🇪🇸 Espagnol", "Es"),
                    ("🇮🇹 Italien", "It"),
                    ("🇩🇪 Allemand", "De"),
                    ("🇨🇳 Chinois", "Cn"),
                ],
                default="🇬🇧 Anglais",
                max_length=32,
            ),
        ),
    ]
