# Generated by Django 4.1.3 on 2022-12-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0030_requestedelementdefault_alter_extragamelanguage_lang"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RequestedElementDefault",
        ),
    ]
