# Generated by Django 4.1.3 on 2023-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0033_game_background_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="request_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="request_name",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="request_tel",
            field=models.BooleanField(default=False),
        ),
    ]
