# Generated by Django 4.1.3 on 2023-01-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0034_alter_game_request_address_alter_game_request_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="can_replay_today",
            field=models.BooleanField(default=False),
        ),
    ]
