# Generated by Django 4.1.3 on 2023-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0035_game_can_replay_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="winnedprice",
            name="price_code",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="winnedprice",
            name="price_qrlocation",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="winnedprice",
            name="price_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="winnedprice",
            name="unlock_link",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
