# Generated by Django 4.1.3 on 2023-01-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0035_game_can_replay_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedelement",
            name="extra_game_language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request_traductions",
                to="games.extragamelanguage",
            ),
        ),
        migrations.AddField(
            model_name="requestedelement",
            name="kind",
            field=models.CharField(
                choices=[("Input", "Input"), ("Checkbox", "Checkbox")],
                default="Input",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="requestedelement",
            name="wording",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
