# Generated by Django 4.1.3 on 2023-01-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0036_winnedprice_price_code_winnedprice_price_qrlocation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="winnedprice",
            name="price_qrlocation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="winnedprice",
            name="unlock_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
