# Generated by Django 4.1.3 on 2023-01-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0036_requestedelement_extra_game_language_and_more"),
        ("games", "0037_alter_winnedprice_price_qrlocation_and_more"),
    ]

    operations = []
