# Generated by Django 4.1.3 on 2023-01-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0038_merge_20230122_1358"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requestedelement",
            name="extra_game_language",
        ),
        migrations.RemoveField(
            model_name="requestedelement",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="requestedelement",
            name="value",
        ),
        migrations.RemoveField(
            model_name="requestedelement",
            name="wording",
        ),
        migrations.CreateModel(
            name="RequestedElementTrads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wording", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "extra_game_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_traductions",
                        to="games.extragamelanguage",
                    ),
                ),
                (
                    "requested_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_elements_lang",
                        to="games.requestedelement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestedElementLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_elements",
                        to="games.lead",
                    ),
                ),
                (
                    "requested_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_elements_lead",
                        to="games.requestedelement",
                    ),
                ),
            ],
        ),
    ]
