# Generated by Django 4.1.3 on 2023-02-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0039_remove_requestedelement_extra_game_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requestedelement",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="requestedelementlead",
            options={"ordering": ("-id",)},
        ),
        migrations.AddField(
            model_name="game",
            name="email_check_override",
            field=models.BooleanField(default=False),
        ),
    ]
