# Generated by Django 4.1.3 on 2023-02-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0042_validatedemail_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="winnedprice",
            name="picked_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
