# Generated by Django 4.1.3 on 2023-02-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0043_winnedprice_picked_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ("id",)},
        ),
    ]
