# Generated by Django 4.1.3 on 2023-02-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0044_alter_price_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="use_qr_for_games",
            field=models.BooleanField(default=False),
        ),
    ]
