# Generated by Django 4.1.3 on 2023-02-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0045_game_use_qr_for_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="automatic_restart_activated",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="automatic_restart_counter_value",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="game",
            name="fullscreen_btn",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="game",
            name="restart_btn",
            field=models.BooleanField(default=True),
        ),
    ]
