# Generated by Django 4.1.3 on 2023-02-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0046_game_automatic_restart_activated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="sound_overide",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
