# Generated by Django 4.1.3 on 2023-03-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0047_game_sound_overide"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="automatic_restart_counter_value",
            field=models.IntegerField(default=20),
        ),
    ]
