# Generated by Django 4.1.3 on 2023-03-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0048_alter_game_automatic_restart_counter_value"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="background_url",
            new_name="bg_image_ingame_url_ovr",
        ),
        migrations.AddField(
            model_name="game",
            name="intro_image_url_landscape_ovr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="intro_image_url_portrait_ovr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
