# Generated by Django 4.1.3 on 2023-03-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0049_rename_background_url_game_bg_image_ingame_url_ovr_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="bg_image_ingame_url_ovr",
            new_name="bg_image_ingame_ovr",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="intro_image_url_landscape_ovr",
            new_name="form_landscape_ovr",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="intro_image_url_portrait_ovr",
            new_name="form_portrait_ovr",
        ),
    ]
