# Generated by Django 4.1.3 on 2023-03-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "games",
            "0050_rename_bg_image_ingame_url_ovr_game_bg_image_ingame_ovr_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="bg_image_ingame_ovr",
            new_name="bg_image_ingame",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="form_landscape_ovr",
            new_name="form_landscape",
        ),
        migrations.RenameField(
            model_name="game",
            old_name="form_portrait_ovr",
            new_name="form_portrait",
        ),
    ]
