# Generated by Django 4.1.3 on 2023-03-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0051_rename_bg_image_ingame_ovr_game_bg_image_ingame_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="bg_image_ingame",
            new_name="bg_ingame",
        ),
    ]
