# Generated by Django 4.1.3 on 2023-03-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0052_rename_bg_image_ingame_game_bg_ingame"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="mailjet_id",
        ),
    ]
