# Generated by Django 4.0 on 2022-11-03 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authie", "0005_useraccount_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[("curtain", "Curtain"), ("Calendar", "Calendar")],
                        default="curtain",
                        max_length=128,
                    ),
                ),
                ("limite_users", models.ManyToManyField(to="authie.UserAccount")),
            ],
        ),
        migrations.CreateModel(
            name="Skin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin",
                    models.CharField(
                        choices=[("base", "Base")], default="base", max_length=128
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skins",
                        to="dash.gametype",
                    ),
                ),
                ("limite_users", models.ManyToManyField(to="authie.UserAccount")),
            ],
        ),
    ]
