# Generated by Django 4.0 on 2022-11-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gametype",
            name="game_type",
        ),
        migrations.RemoveField(
            model_name="skin",
            name="skin",
        ),
        migrations.AddField(
            model_name="gametype",
            name="name",
            field=models.CharField(default="curtain", max_length=32),
        ),
        migrations.AddField(
            model_name="skin",
            name="name",
            field=models.CharField(default="Base", max_length=32),
        ),
    ]
