# Generated by Django 4.0 on 2022-11-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0005_useraccount_uuid"),
        ("dash", "0002_remove_gametype_game_type_remove_skin_skin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gametype",
            name="limite_users",
            field=models.ManyToManyField(
                blank=True, null=True, to="authie.UserAccount"
            ),
        ),
        migrations.AlterField(
            model_name="skin",
            name="limite_users",
            field=models.ManyToManyField(
                blank=True, null=True, to="authie.UserAccount"
            ),
        ),
    ]
