# Generated by Django 3.2.16 on 2022-11-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0004_skin_game_and_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametype",
            name="ref_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="skin",
            name="ref_id",
            field=models.IntegerField(default=1),
        ),
    ]
