# Generated by Django 3.2.16 on 2022-11-13 11:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0005_auto_20221113_1046"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gametype",
            name="limite_users",
        ),
        migrations.RemoveField(
            model_name="skin",
            name="limite_users",
        ),
        migrations.AddField(
            model_name="gametype",
            name="limited_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default="{1}",
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skin",
            name="limited_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                default="{2}",
                size=None,
            ),
            preserve_default=False,
        ),
    ]
