# Generated by Django 3.2.16 on 2022-11-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0005_useraccount_uuid"),
        ("dash", "0006_auto_20221113_1124"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gametype",
            name="limited_users",
        ),
        migrations.AddField(
            model_name="gametype",
            name="limited_users",
            field=models.ManyToManyField(
                blank=True, null=True, to="authie.UserAccount"
            ),
        ),
        migrations.RemoveField(
            model_name="skin",
            name="limited_users",
        ),
        migrations.AddField(
            model_name="skin",
            name="limited_users",
            field=models.ManyToManyField(
                blank=True, null=True, to="authie.UserAccount"
            ),
        ),
    ]
