# Generated by Django 4.1.3 on 2023-02-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authie", "0015_gamedefaults_policy_rules_gamedefaults_regulation"),
        ("dash", "0007_auto_20221113_1133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gametype",
            name="limited_users",
            field=models.ManyToManyField(blank=True, to="authie.useraccount"),
        ),
        migrations.AlterField(
            model_name="skin",
            name="limited_users",
            field=models.ManyToManyField(blank=True, to="authie.useraccount"),
        ),
    ]
