# Generated by Django 4.1.3 on 2023-04-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0008_alter_gametype_limited_users_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="skin",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
